ProyectoAdiuvo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from Usuarios import views as UsuariosViews
from Proyectos import views
from Proyectos import urls
from localizacion import views
from localizacion import urls

urlpatterns = [
    url(r'^admin/',admin.site.urls),
    url(r'^admin/',include('Usuarios.urls')),
    url(r'^admin/',include('Proyectos.urls')),
    url(r'^redactor/', include('redactor.urls')),
    url(r'^propuesta/', include('Proyectos.urls')),
    url(r'^admin/', include('localizacion.urls')),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^enivar_notificaciones/',UsuariosViews.enivar_notificaciones, name="enivar-notificaciones"),
    url(r'^actualizar_noti/',UsuariosViews.actualizar_noti, name="actualizar_noti"),
    url(r'^guardar_notificaciones/',UsuariosViews.guardar_notificaciones, name="guardar-notificaciones"),
    #url(r'^reporte_proyectos_pdf/$',login_required(ReporteProyectosPDF.as_view()), name="reporte_proyectos_pdf"),
    # url(r'^advanced_filters/', include('advanced_filters.urls'))

]
if settings.DEBUG:
   urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proyectos/urls.py
from django.conf.urls import url
from Proyectos import views


urlpatterns = [
	url(r'^informacion/(?P<pk>[0-9]+)/$', views.info_post, name="informacion"),
	url(r'^postu_a_convo/(?P<pk>[0-9]+)/$', views.postulacion_a_convocatoria),
	url(r'^save_propu/', views.save_propuesta),
	url(r'^pdf/(?P<pdf_pk>[0-9]+)/$', views.generar_pdf,  name='generar_pdf'),
	url(r'^enviar_documentos/',views.enviar_documentos, name="enviar-documentos"),
	url(r'^get_documento_resultado/',views.get_documeto, name="get-get-documento-resultado"),
	url(r'^encuesta/',views.encuesta, name ="encuesta" ),
	url(r'^realizar_encuesta',views.realizar_encuesta, name ="realizar_encuesta"),
	url(r'^sugerencia', views.sugerencia),
	url(r'enviar_sugerencia', views.enviar_sugerencia, name= 'enviar_sugerencia'),
	url(r'^get_evaluacion/',views.get_evaluacion, name="get-evaluacion"),
	url(r'^guardar_actividad/', views.guardar_actividad),
	url(r'^get_datos_actividad/', views.get_datos_actividad),
	
]

Usuarios/urls.py
from django.conf.urls import url
from Usuarios import views

urlpatterns = [

url(r'^Save_user/', views.signUp, name="api-save-usuario"),
url(r'^sign-up/', views.showSignUp, name="api-show-usuario"),
]

Usuarios/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.db import models
from Proyectos.models import *

class ob_usuarios(AbstractUser):
	us_fecha_creacion = models.DateTimeField(auto_now_add=True,verbose_name="Fecha de creacion")
	us_profecion = models.CharField(verbose_name='Profesión',blank=True,null=True,max_length=200)
	us_entidad = models.CharField(verbose_name="Entidad", blank=True,null=True,max_length=200)
	us_fecha_na = models.DateField(verbose_name="Fecha de cumpleaños",blank=True,null=True,max_length=300)
	GENERO = (
		('M',"Masculino"),
		('F',"Femenino"),
		('O',"Otro"),
		)
	us_genero = models.CharField(verbose_name="Género",max_length=20,blank=True,null=True,choices=GENERO)
	us_universidad = models.CharField(verbose_name="Universidad",max_length=200,blank=True,null=True)
	us_max_titulo = models.CharField(verbose_name="Máximo titulo alcanzado",max_length=200,blank=True,null=True)
	us_eres_profe = models.BooleanField(verbose_name="Eres profesor",default=False)

	class Meta:
		verbose_name="Usuario"
		verbose_name_plural="Usuarios"


class notificaciones(models.Model):
	usuario=models.ForeignKey('ob_usuarios',blank=True,null=True,verbose_name="De")
	para=models.ForeignKey('ob_usuarios',blank=True,null=True,verbose_name="Para", related_name="para")
	mensaje=models.TextField(max_length=255,blank=True,null=True,verbose_name="Mensaje")
	estado=models.BooleanField(verbose_name="visto", default=False)
	D_fechaCreacion = models.DateTimeField( verbose_name="Fecha creación",auto_now_add=True, blank = True, null=True)


	def __unicode__(self):
			return u"De: %s Para: %s" %(self.usuario, self.para)
			
	def __str__(self):
			return u"De: %s Para: %s" %(self.usuario, self.para)
	class Meta:
		verbose_name=u'Notificación'
		verbose_name_plural=u'Notificaciones'






Proyectos/forms.py
from django import forms
from .models import *

# class PropuestaForm(forms.ModelForm):

#     class Meta:
#         model = propuesta
#         fields = ('titulo', 'resumen', 'pregunta')

class propuestaDetalleFecha(ModelForm):
    fechaCreacion =  forms.DateField(widget=forms.TextInput(attrs={'class':'datepicker'}),required=True,input_formats=['%d/%m/%Y',])
 
    class Meta:
        model = propuesta

Proyectos/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from .models import *
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from .models import encuestas
from .models import sugerencias
from django.conf import settings
from io import BytesIO
from django.views.generic import View, ListView
from Proyectos.utils import render_to_pdf #created in step 4
from django.shortcuts import render, get_object_or_404


# @staff_member_required
# def get_queryset(self):
#     return convocatoria.objects


@staff_member_required
@login_required(login_url='/')
@csrf_exempt
def postulacion_a_convocatoria(request,pk):
    if(request.method=="GET"):
        convocatoria_nombre = get_object_or_404(convocatoria, pk=pk)
        tematicas_pk = propuesta_tematica.objects.all()
        context_dict = {'tematicas': tematicas_pk}

        return render(request, "post_a_convocatoria.html", {'convocatoria':convocatoria_nombre, 'tematicas':tematicas_pk})

@staff_member_required
@login_required(login_url='/')
@csrf_exempt
def save_propuesta(request):
    json =[]
    pk_new = 0
    if request.method == "POST":
        propuesta_pk = request.POST['propuesta_pk']
        convocatoria_ = request.POST['pk_convocatoria']
        titulo_ = request.POST['titulo_propuesta']
        resumen_ = request.POST['resumen_propuesta']
        justificacion_ = request.POST['justificacion']
        pregunta_ = request.POST['pregunta_propuesta']
        tematica_ = request.POST['tematica']
        solucion_ = request.POST['solucion_propuesta']
        deter_ = request.POST.get("determinantes")
        if (propuesta_pk=="NaN"):
            try:
                propuesta_check = propuesta.objects.filter(convocatoria__pk=convocatoria_ , usuario = request.user)[0]
                mensaje = "ya-postulado"
                pk_new = propuesta_check.pk


                status_dir = {}
                status_dir["status"] = mensaje

                status_dir["pk_propuesta"] = pk_new
                json.append(status_dir)
                
            except Exception as e:
                
                obj_post = propuesta()
                mensaje = "insert"    
                obj_post.convo_nombre = convocatoria.objects.get(pk=convocatoria_)
                obj_post.user = request.user
                obj_post.prop_titulo = titulo_
                obj_post.prop_resumen_desafio = resumen_
                obj_post.prop_pregunta_desafio = pregunta_
                determinants = deter_.replace(';', ',')
                obj_post.det_determinantes = determinants
                obj_post.tem_tematicas = propuesta_tematica.objects.get(pk = tematica_)
                obj_post.prop_justificacion = justificacion_
                obj_post.prop_solucion = solucion_
                obj_post.save()

                status_dir = {}
                status_dir["status"] = mensaje
                status_dir["pk_propuesta"] = obj_post.pk
                status_dir["determinants"] = obj_post.det_determinantes
                json.append(status_dir)
                return JsonResponse(json, safe=False)
        else:
            obj_post = propuesta.objects.get(pk = propuesta_pk)
            mensaje = "update"

            obj_post.convo_nombre = convocatoria.objects.get(pk=convocatoria_)
            obj_post.user = request.user
            obj_post.prop_titulo = titulo_
            obj_post.prop_resumen_desafio = resumen_
            obj_post.prop_pregunta_desafio = pregunta_
            obj_post.tem_tematicas = propuesta_tematica.objects.get(pk = tematica_)
            obj_post.prop_justificacion = justificacion_
            obj_post.prop_solucion = solucion_
            obj_post.save()

            status_dir = {}
            status_dir["status"] = mensaje
            status_dir["pk_propuesta"] = obj_post.pk
            json.append(status_dir)
            return JsonResponse(json, safe=False)
    return JsonResponse(json, safe=False)


@login_required(login_url='/')
@csrf_exempt
def view_deter(request):
    propuesta_check = propuesta.objects.get(pk=pk)
    deter_obj = propuesta_check.det_determinantes
    return render(request, "post_a_convocatoria.html")
    


@staff_member_required
@login_required(login_url='/')
@csrf_exempt
def guardar_actividad(request): 
    json = []
    dtr = ""
    pk_new = 0
    if request.method=="POST":
        propuesta_pk = request.POST['propuesta_pk']
        voluntario = request.POST['voluntario_']
        actividad_text = request.POST['actividad_']
        duracion = request.POST['duracion_']
        metodologia = request.POST['metodologia']
        riesgos = request.POST['riesgos_']
        presupuesto = request.POST['presupuesto_']
        tipo_voluntario = request.POST['tipo_voluntario']
        # pk_actividad_ = request.POST['pk_actividad_']
        cotizacion = request.FILES['cotizacion_']
        propuesta_check = propuesta.objects.get(pk=propuesta_pk)

        # pos_ = None
        # actividad_ = None

        pos_ = actividade.objects.filter(act_propuesta=propuesta_check).count()
        
        actividad_ = actividade()
        actividad_.act_propuesta = propuesta_check
        actividad_.act_actividades = actividad_text
        actividad_.act_metodologia = metodologia
        actividad_.act_tiempo = duracion
        actividad_.act_presupuesto = presupuesto
        actividad_.act_cotizacion = cotizacion
        actividad_.act_riesgo = riesgos
        if voluntario == "SI":
            actividad_.act_voluntario = True
        elif voluntario == "NO":
            actividad_.act_voluntario = False
        actividad_.act_tipo_voluntario = tipo_voluntario
        actividad_.save()
        actividad_obj = actividade.objects.filter(act_propuesta=propuesta_check)
        total = 0
        for actividad in actividad_obj:
            total += int(actividad.act_presupuesto)

        mensaje = "insert"
        pk_new = propuesta_check.pk            
        status_dir = {}
        status_dir["status"] = mensaje

        # propuesta_check.presupuesto = total
        # propuesta_check.save()
        # print propuesta_check.presupuesto


        # if (pk_actividad_==""):
        status_dir["es_nuevo"] = "SI"
        status_dir["pk_actividad"] = actividad_.pk
        status_dir["actividad_"] = actividad_.act_actividades
        status_dir["riesgos_"] = actividad_.act_riesgo
        status_dir["metodologia"] = actividad_.act_metodologia
        status_dir["actividad_"] = actividad_.act_actividades 
        status_dir["duracion_"] = actividad_.act_tiempo 
        status_dir["presupuesto_"] = "$ "+str('{:,}'.format(float(actividad_.act_presupuesto)))    
        status_dir["presupuesto"] ="$ "+str('{:,}'.format(total))  
        # else:
        #     status_dir["es_nuevo"] = "NO"

        #     status_dir["pk_actividad"] = actividad_.pk 
        #     status_dir["riesgos_"] = actividad_.act_riesgo
        #     status_dir["metodologia"] = actividad_.act_metodologia 
        #     status_dir["cotizacion_"] = actividad_.act_cotizacion
        #     status_dir["actividad_"] = actividad_.act_actividades 
        #     status_dir["duracion_"] = actividad_.act_tiempo 
        #     status_dir["presupuesto_"] = "$ "+str('{:,}'.format(float(actividad_.act_presupuesto)))    
        #     status_dir["presupuesto"] ="$ "+str('{:,}'.format(total))  

        status_dir["pk_propuesta"] = pk_new

        json.append(status_dir)
    print dtr
    
    return JsonResponse(json,safe=False)
    




@login_required(login_url='/')
@csrf_exempt
def guardar_resultados_esperados(request): 
    json =[]
    pk_new = 0
    if (request.method=="POST"):
        propuesta_pk = request.POST['propuesta_pk']
        resultados_esperado_ = request.POST['resultados_esperado_']
        cantidad_resultado_esperado = request.POST['cantidad_resultado_esperado']
        unidad_resultado_esperado = request.POST['unidad_resultado_esperado']
        
        propuesta_check = propuesta.objects.get(pk=propuesta_pk)
        resultado = r_esperado()
        resultado.unidad = unidad_resultado_esperado
        resultado.cantidad = cantidad_resultado_esperado
        resultado.resultados_esperados = resultados_esperado_
        resultado.usuario = request.user
        resultado.propuesta = propuesta_check
        resultado.save()

        mensaje = "insert"
        pk_new = propuesta_check.pk
        status_dir = {}
        status_dir["status"] = mensaje

        status_dir["resultados_esperado_"] = resultado.resultados_esperados
        status_dir["cantidad_resultado_esperado"] = resultado.cantidad
        status_dir["unidad_resultado_esperado"] = resultado.unidad 
        status_dir["pk_resultado_esperado"] = resultado.pk

        status_dir["pk_propuesta"] = pk_new
        json.append(status_dir) 

 
    return JsonResponse(json,safe=False) 




@login_required(login_url='/')
@csrf_exempt 
def get_datos_actividad(request): 
    json =[]
    pk_new = 0
    if (request.method=="POST"):
        pk_actividad = request.POST['pk_actividad']
        pk_propuesta = request.POST['pk_propuesta']
        mensaje =""
        actividad  = actividade.objects.get(pk=pk_actividad)
        
        if actividad!=None:
            status_dir = {}
            status_dir["pk"] = actividad.pk
            status_dir["riesgos_"] = actividad.act_riesgo
            status_dir["metodologia"] = actividad.act_metodologia 
            # status_dir["cotizacion_"] = actividad.act_cotizacion
            status_dir["actividad_"] = actividad.act_actividades 
            status_dir["duracion_"] = actividad.act_tiempo

Proyectos/templates/proyecto/archivos_inline.html
{% load i18n admin_urls static admin_modify %}
<div class="js-inline-admin-formset inline-group" id="{{ inline_admin_formset.formset.prefix }}-group"
     data-inline-type="tabular"
     data-inline-formset="{{ inline_admin_formset.inline_formset_data }}">
  <div class="tabular inline-related {% if forloop.last %}last-related{% endif %}">
{{ inline_admin_formset.formset.management_form }}
<fieldset class="module {{ inline_admin_formset.classes }}">
   <h2>{{ inline_admin_formset.opts.verbose_name_plural|capfirst }}</h2>
   {{ inline_admin_formset.formset.non_form_errors }}
   <table>
     <thead><tr>
       <th class="original"></th>
     {% for field in inline_admin_formset.fields %}
       {% if not field.widget.is_hidden %}
         <th{% if field.required %} class="required"{% endif %}>{{ field.label|capfirst }}
         {% if field.help_text %}&nbsp;<img src="{% static "admin/img/icon-unknown.svg" %}" class="help help-tooltip" width="10" height="10" alt="({{ field.help_text|striptags }})" title="{{ field.help_text|striptags }}" />{% endif %}
         </th>
       {% endif %}
     {% endfor %}
     {% if inline_admin_formset.formset.can_delete %}<th>{% trans "Delete?" %}</th>{% endif %}
     </tr></thead>

     <tbody>
     {% for inline_admin_form in inline_admin_formset %}
        {% if inline_admin_form.form.non_field_errors %}
        <tr><td colspan="{{ inline_admin_form|cell_count }}">{{ inline_admin_form.form.non_field_errors }}</td></tr>
        {% endif %}
        <tr class="form-row {% cycle "row1" "row2" %} {% if inline_admin_form.original or inline_admin_form.show_url %}has_original{% endif %}{% if forloop.last %} empty-form{% endif %}"
             id="{{ inline_admin_formset.formset.prefix }}-{% if not forloop.last %}{{ forloop.counter0 }}{% else %}empty{% endif %}">
        <td class="original">
          {% if inline_admin_form.original or inline_admin_form.show_url %}<p>
          {% if inline_admin_form.original %}
          {{ inline_admin_form.original }}
          {% if inline_admin_form.model_admin.show_change_link and inline_admin_form.model_admin.has_registered_model %}<a href="{% url inline_admin_form.model_admin.opts|admin_urlname:'change' inline_admin_form.original.pk|admin_urlquote %}" class="inlinechangelink">{% trans "Change" %}</a>{% endif %}
          {% endif %}
          {% if inline_admin_form.show_url %}<a href="{{ inline_admin_form.absolute_url }}">{% trans "View on site" %}</a>{% endif %}
            </p>{% endif %}
          {% if inline_admin_form.needs_explicit_pk_field %}{{ inline_admin_form.pk_field.field }}{% endif %}
          {{ inline_admin_form.fk_field.field }}
          {% spaceless %}
          {% for fieldset in inline_admin_form %}
            {% for line in fieldset %}
              {% for field in line %}
                {% if field.field.is_hidden %} {{ field.field }} {% endif %}
              {% endfor %}
            {% endfor %}
          {% endfor %}
          {% endspaceless %}
        </td>
        {% for fieldset in inline_admin_form %}
          {% for line in fieldset %}
            {% for field in line %}
              {% if not field.field.is_hidden %}
              <td{% if field.field.name %} class="field-{{ field.field.name }}"{% endif %}>
              {% if field.is_readonly %}
                  <p>{{ field.contents }}</p>
              {% else %}
                  {{ field.field.errors.as_ul }}
                  {{ field.field }}
              {% endif %}
              </td>
              {% endif %}
            {% endfor %}
          {% endfor %}
        {% endfor %}
        {% if inline_admin_formset.formset.can_delete %}
          <td class="delete">{% if inline_admin_form.original %}{{ inline_admin_form.deletion_field.field }}{% endif %}</td>
        {% endif %}
        </tr>
     {% endfor %}
     </tbody>
   </table>
</fieldset>
  </div>
</div>

Proyectos/templates/proyecto/info_actividades.html
<fieldset class="suit-form">
    <h2>Información importante</h2>

    <!--<div class="description">This is another custom form include example</div>-->

    <div class="form-group row form-row" style=" background-color: rgb(228, 228, 228) !important; -webkit-box-shadow: 1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;-moz-box-shadow:    1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;box-shadow:         1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Recuerda que... 
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="nombre_con">
             {% if original.estado == "EE" %}

                <ul>
                <li><p> Ya comenzaste a ejecutar tu proyecto.
                <li><p>Nos interesa que vayas organizando las actividades realizadas y el presupuesto gastado. Cuéntanos cuánto te has gastado en cada actividad, suma y pon ese valor en la casilla "Presupuesto". Incluye, por ejempo,  <strong>insumos, mano de obra, compras, entre otros. </strong></p></li>
                {% if change%}
                <li><p>En la parte inferior vas a poder ir viendo el presupuesto disponible que tienes después de los gastos realizados,</p></li>
                <li><p>Agradecemos evidencias fotográficas del proceso. ¡Nos encanta ver los resultados de tus esfuerzos! Historias, anécdotas, problemas y soluciones. Todo nos sirve para ayudarte a llevar a cabo el proyecto de la mejor manera. Recuerda que las personas que apoyaron tu proyecto quieren saber detalles.</p></li>

                {% endif%}
                </ul>

            {% else %}
                <ul>
                <li><p>La estimación del tiempo para realizar una actividad debe ser tomada en <strong> días, semanas, meses, años.</strong> Ejemplo: 2 días, 1 semana.</p></li>
                <li><p>Suma todo lo que costará la actividad, que incluya, por ejempo,  <strong>insumos, mano de obra, compras, entre otros. </strong> Esta suma corresponde al presupuesto de la actividad.</p></li>
                {% if change%}
                <li><p>En este cuadro puedes organizar las actividades, añadiendo, cambiando el orden e incluso eliminando aquellas que no consideres necesarias. La idea es que te puedas organizar. Recuerda que el presupuesto es inamovible.</p></li>
                {% endif%}
                </ul>

  
            {% endif %}
            </div>
        </div>
    </div>
</fieldset>

Proyectos/templates/proyecto/info_evaluacion.html
<fieldset class="suit-form">
    <h2></h2>

    <!--<div class="description">This is another custom form include example</div>-->

    <div class="form-group row form-row">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Nombre del proyecto
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="nombre_pro">
                   {% if original.proyecto.pk %}
                    <p>{{ original.proyecto.prop_titulo }} </p>

                {% else %}
                    <div class="text-muted">
                       El elemento aún no se ha guardado
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="form-group row form-row" style=" background-color: rgb(228, 228, 228) !important; -webkit-box-shadow: 1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;-moz-box-shadow:    1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;box-shadow:         1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;" >
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Puntaje
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9" >
            <div class="form-control-static" id="nombre_con">
             {% if  change %}
                <h1 id="puntaje">{{original.proyecto.puntaje}}</h1>
            {% else %}
            <h1 id="puntaje">0</h1>
            {% endif%}

            </div>
        </div>
    </div>
</fieldset>

Proyectos/templates/proyecto/info_general.html
<fieldset class="suit-form">
    <h2>Información importante</h2>

    <!--<div class="description">This is another custom form include example</div>-->

    <div class="form-group row form-row" style=" background-color: rgb(228, 228, 228) !important; -webkit-box-shadow: 1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;-moz-box-shadow:    1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;box-shadow:         1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Recuerda que... 
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="nombre_con">
                <ul>
                <li><p>Recuerda que una parte importante del éxito es la participación de representantes de la comunidad. Añade los miembros que hacen parte de tu equipo y que se han responsabilizado por un rol.</p></li>

            </div>
        </div>
    </div>
</fieldset>




 

Proyectos/templates/proyecto/info_proyecto.html
<fieldset class="suit-form">
    <h2>Convocatoria</h2>

    <!--<div class="description">This is another custom form include example</div>-->

    <div class="form-group row form-row">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Nombre de la convocatoria
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="nombre_con">
                   {% if original.convocatoria.pk %}
                    <p>{{ original.convocatoria.nombre }} </p>

                {% else %}
                    <div class="text-muted">
                       El elemento aún no se ha guardado
                    </div>
                {% endif %}
            </div>
        </div>
    </div>


    <div class="form-group row form-row">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Convocatoria
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="foto_con">
                {% if original.convocatoria.pk %}
                    <img src="{{ original.convocatoria.imagen.url }}" alt="" class="img-fluid img-thumbnail" style="max-width: 200px" >

                {% else %}
                    <div class="text-muted">
                       El elemento aún no se ha guardado
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
  {% if change %}
    <div class="form-group row form-row">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Estado del proyecto
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9">
            <div class="form-control-static" id="foto_con">
                {% if original.estado != none %}
                     <h4>{{ original.get_estado_display }} </h4>

                {% else %}
                    <div class="text-muted">
                       El elemento aún no se ha guardado
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
 {% endif %}
</fieldset>

Proyectos/templates/proyecto/info_resultados.html
<fieldset class="suit-form">
    <h2>Información importante</h2>

    <!--<div class="description">This is another custom form include example</div>-->

    <div class="form-group row form-row" style=" background-color: rgb(228, 228, 228) !important; -webkit-box-shadow: 1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;-moz-box-shadow:    1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;box-shadow:         1px 0px 30px 0px rgba(50, 50, 50, 0.25) !important;">
        <label class="form-control-label col-xs-12 col-sm-3 col-md-2">
            Recuerda que... 
        </label>
        <div class="col-xs-12 col-sm-9 col-md-10 col-lg-9" >
            <div class="form-control-static" id="nombre_con">
             {% if original.estado == "E" %}
                <ul>
                <li><p>Puedes estar teniendo uno o más tipos de impactos esperados. Buscamos soluciones con efectos transversales que afecten todo el desarrollo de los estudiantes.</p></li>
                {% if change%}
                <li><p>En este momento puedes incluir nuevos resultados identificados. Si han pasado nuevas cosas increíbles, inclúyelas aquí.   </p></li>
                <li><p>Sé muy específico y cuéntanos en palabras cómo ves el impacto generado. Incluye fotos o videos. </p></li>
                {% endif%}
                </ul>

             {% else %}
                <ul>
                <li><p>Puedes tener uno o más tipos de impactos esperados. Buscamos soluciones con efectos transversales que afecten todo el desarrollo de los estudiantes.</p></li>
            {% endif%}

            </div>
        </div>
    </div>
</fieldset>